### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by zeidk** [popftif/popf-tif#1]
Hello,

I'm trying to install this planner on Ubuntu 16.04.
Running ./build-instructions.txt tells me

-- Could NOT find concert (missing:  CONCERT_INCLUDES CONCERT) 
-- Could NOT find cplex (missing:  CPLEX_INCLUDES CPLEX ILOCPLEX) 

How do I get to install the missing tools?

Thank you

**Comment by chiarapiacentini** [comment]
Hi,

you do not actually need CPLEX to run the planner. I modified the cmake, so that you can compile the planner using only the CLP libraries. If you want to use CPLEX anyway, you can download the software on the IBM website. It requires a license, which is free for academic use.

Thank you
